
// 公共图标
const Icon = {
    iconStar: require('../images/iconStar.png'),
    iconSearch: require('../images/iconSearch.png'),
    iconOperation: require('../images/iconOperation.png'),
    iconBooks: require('../images/iconbooks.png'),
    iconBlackArrowLeft: require('../images/iconBlackArrowLeft.png'),
    iconBookSelect: require('../images/iconBookSelect.png'),
    iconGrayArrowBottom: require('../images/iconGrayArrowBottom.png'),
    iconGrayArrowTop: require('../images/iconGrayArrowTop.png'),
    iconHome: require('../images/iconHome.png'),
    iconCheck: require('../images/icon_check_in.png'),
    iconLibrary: require('../images/iconLibrary.png'),
    iconRank: require('../images/iconRank.png'),
    iconLogout: require('../images/iconLogout.png'),
    iconQQ: require('../images/qq_login.png'),
    iconWX: require('../images/wechat_login.png'),
    iconWB: require('../images/weibo_login.png'),
    iconIntroMenu: require('../images/icon_intro_menu.png'),
    iconLikeFinger: require('../images/icon_like_finger.png'),
    iconRmb: require('../images/icon_rmb.png'),
    iconChapter: require('../images/icon_chapter_menu.png'),
    iconTextSize: require('../images/icon_text_size.png'),
    iconMoon: require('../images/icon_moon.png'),
    iconPencil: require('../images/icon_pencil.png'),
    iconNoCollection: require('../images/no_collection.png'),
    iconCheckInfo: require('../images/icon_check_info.png'),
    iconCheckTitle: require('../images/check_title.png'),
    iconCheckCoin: require('../images/check_coin.png'),
    iconCheckGift: require('../images/check_gift.png'),
    iconCheckTic: require('../images/check_tic.png'),
    iconRuleClose: require('../images/icon_rule_close.png'),
    iconNoBookMark: require('../images/no_bookmark.png'),
    iconNoWifi: require('../images/no_wifi.png'),
    iconSun: require('../images/icon_sun.png'),
    iconGestureMenu: require('../images/gesture_menu.png'),
    iconGestureNextPage: require('../images/gesture_next_page.png'),
    iconGesturePreviewPage: require('../images/gesture_preview_page.png'),
    iconInviteCode: require("../images/icon_invite_code.png"),
    iconBookDefaultBig: require('../images/book_defaut_big.png'),
    iconBookDefaultSmall: require('../images/book_defaut_small.png'),
    iconCommentAvtarDefault: require('../images/comment_avtar_default.png')
};

export default Icon;